name: test

on:
  push:

jobs:
  build:
    runs-on: macos-latest
    name: Build assets
    environment: production
    steps:
      - uses: actions/checkout@v4
      - name: Cache pnpm modules
        uses: actions/cache@v3
        with:
          path: ~/.pnpm-store
          key: ${{ runner.os }}-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-
      - uses: pnpm/action-setup@v2.4.0
        with:
          version: latest
          run_install: true
      - name: Use Node.js 16.x
        uses: actions/setup-node@v4.0.1
        with:
          node-version: 16.x
          cache: "pnpm"
      - name: Package the extension for Chrome
        run: pnpm build --zip
      - name: Package the extension for Firefox
        run: pnpm build:firefox --zip
      - name: Package the extension for Safari
        run: pnpm build:safari:zip
      - name: Archive production artifacts
        uses: actions/upload-artifact@v4
        with:
          name: build
          path: |
            build/safari-mv3-prod.zip
            build/chrome-mv3-prod.zip
            build/firefox-mv3-prod.zip
